"""Add MedDRA tables

Revision ID: 83c5f451581d
Revises: 7ab3c912d4ef
Create Date: 2026-01-20 07:43:12.526451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c5f451581d'
down_revision = '7ab3c912d4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'meddra_hlgt' not in tables:
        op.create_table('meddra_hlgt',
        sa.Column('hlgt_code', sa.Integer(), nullable=False),
        sa.Column('hlgt_name', sa.String(length=255), nullable=False),
        sa.Column('hlgt_whoart_code', sa.String(length=20), nullable=True),
        sa.Column('hlgt_harts_code', sa.Integer(), nullable=True),
        sa.Column('hlgt_costart_code', sa.String(length=20), nullable=True),
        sa.Column('hlgt_icd9_code', sa.String(length=20), nullable=True),
        sa.Column('hlgt_icd9cm_code', sa.String(length=20), nullable=True),
        sa.Column('hlgt_icd10_code', sa.String(length=20), nullable=True),
        sa.Column('hlgt_currency', sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint('hlgt_code')
        )
    
    if 'meddra_hlt' not in tables:
        op.create_table('meddra_hlt',
        sa.Column('hlt_code', sa.Integer(), nullable=False),
        sa.Column('hlt_name', sa.String(length=255), nullable=False),
        sa.Column('hlt_whoart_code', sa.String(length=20), nullable=True),
        sa.Column('hlt_harts_code', sa.Integer(), nullable=True),
        sa.Column('hlt_costart_code', sa.String(length=20), nullable=True),
        sa.Column('hlt_icd9_code', sa.String(length=20), nullable=True),
        sa.Column('hlt_icd9cm_code', sa.String(length=20), nullable=True),
        sa.Column('hlt_icd10_code', sa.String(length=20), nullable=True),
        sa.Column('hlt_currency', sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint('hlt_code')
        )

    if 'meddra_pt' not in tables:
        op.create_table('meddra_pt',
        sa.Column('pt_code', sa.Integer(), nullable=False),
        sa.Column('pt_name', sa.String(length=255), nullable=False),
        sa.Column('null_field', sa.String(length=1), nullable=True),
        sa.Column('pt_soc_code', sa.Integer(), nullable=True),
        sa.Column('pt_whoart_code', sa.String(length=20), nullable=True),
        sa.Column('pt_harts_code', sa.Integer(), nullable=True),
        sa.Column('pt_costart_code', sa.String(length=20), nullable=True),
        sa.Column('pt_icd9_code', sa.String(length=20), nullable=True),
        sa.Column('pt_icd9cm_code', sa.String(length=20), nullable=True),
        sa.Column('pt_icd10_code', sa.String(length=20), nullable=True),
        sa.Column('pt_currency', sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint('pt_code')
        )

    if 'meddra_smq_list' not in tables:
        op.create_table('meddra_smq_list',
        sa.Column('smq_code', sa.Integer(), nullable=False),
        sa.Column('smq_name', sa.String(length=255), nullable=False),
        sa.Column('smq_level', sa.Integer(), nullable=True),
        sa.Column('smq_description', sa.Text(), nullable=True),
        sa.Column('smq_source', sa.String(length=255), nullable=True),
        sa.Column('smq_note', sa.Text(), nullable=True),
        sa.Column('meddra_version', sa.String(length=10), nullable=True),
        sa.Column('status', sa.String(length=1), nullable=True),
        sa.Column('smq_algorithm', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('smq_code')
        )

    if 'meddra_soc' not in tables:
        op.create_table('meddra_soc',
        sa.Column('soc_code', sa.Integer(), nullable=False),
        sa.Column('soc_name', sa.String(length=255), nullable=False),
        sa.Column('soc_abbrev', sa.String(length=50), nullable=True),
        sa.Column('soc_whoart_code', sa.String(length=20), nullable=True),
        sa.Column('soc_harts_code', sa.Integer(), nullable=True),
        sa.Column('soc_costart_code', sa.String(length=20), nullable=True),
        sa.Column('soc_icd9_code', sa.String(length=20), nullable=True),
        sa.Column('soc_icd9cm_code', sa.String(length=20), nullable=True),
        sa.Column('soc_icd10_code', sa.String(length=20), nullable=True),
        sa.Column('soc_currency', sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint('soc_code')
        )

    if 'meddra_llt' not in tables:
        op.create_table('meddra_llt',
        sa.Column('llt_code', sa.Integer(), nullable=False),
        sa.Column('llt_name', sa.String(length=255), nullable=False),
        sa.Column('pt_code', sa.Integer(), nullable=True),
        sa.Column('llt_whoart_code', sa.String(length=20), nullable=True),
        sa.Column('llt_harts_code', sa.Integer(), nullable=True),
        sa.Column('llt_costart_code', sa.String(length=20), nullable=True),
        sa.Column('llt_icd9_code', sa.String(length=20), nullable=True),
        sa.Column('llt_icd9cm_code', sa.String(length=20), nullable=True),
        sa.Column('llt_icd10_code', sa.String(length=20), nullable=True),
        sa.Column('llt_currency', sa.String(length=1), nullable=True),
        sa.ForeignKeyConstraint(['pt_code'], ['meddra_pt.pt_code'], ),
        sa.PrimaryKeyConstraint('llt_code')
        )

    if 'meddra_mdhier' not in tables:
        op.create_table('meddra_mdhier',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pt_code', sa.Integer(), nullable=False),
        sa.Column('hlt_code', sa.Integer(), nullable=False),
        sa.Column('hlgt_code', sa.Integer(), nullable=False),
        sa.Column('soc_code', sa.Integer(), nullable=False),
        sa.Column('pt_name', sa.String(length=255), nullable=True),
        sa.Column('hlt_name', sa.String(length=255), nullable=True),
        sa.Column('hlgt_name', sa.String(length=255), nullable=True),
        sa.Column('soc_name', sa.String(length=255), nullable=True),
        sa.Column('soc_abbrev', sa.String(length=50), nullable=True),
        sa.Column('null_field', sa.String(length=1), nullable=True),
        sa.Column('pt_soc_code', sa.Integer(), nullable=True),
        sa.Column('primary_soc_fg', sa.String(length=1), nullable=True),
        sa.ForeignKeyConstraint(['hlgt_code'], ['meddra_hlgt.hlgt_code'], ),
        sa.ForeignKeyConstraint(['hlt_code'], ['meddra_hlt.hlt_code'], ),
        sa.ForeignKeyConstraint(['pt_code'], ['meddra_pt.pt_code'], ),
        sa.ForeignKeyConstraint(['soc_code'], ['meddra_soc.soc_code'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('meddra_mdhier', schema=None) as batch_op:
            batch_op.create_index('idx_mdhier_pt', ['pt_code'], unique=False)
            batch_op.create_index('idx_mdhier_soc', ['soc_code'], unique=False)

    if 'meddra_smq_content' not in tables:
        op.create_table('meddra_smq_content',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('smq_code', sa.Integer(), nullable=False),
        sa.Column('term_code', sa.Integer(), nullable=False),
        sa.Column('term_level', sa.Integer(), nullable=False),
        sa.Column('term_scope', sa.Integer(), nullable=True),
        sa.Column('term_category', sa.String(length=1), nullable=True),
        sa.Column('term_weight', sa.Integer(), nullable=True),
        sa.Column('term_status', sa.String(length=1), nullable=True),
        sa.Column('term_addition_version', sa.String(length=10), nullable=True),
        sa.Column('term_last_modified_version', sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(['smq_code'], ['meddra_smq_list.smq_code'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('meddra_smq_content', schema=None) as batch_op:
            batch_op.create_index('idx_smq_content_smq', ['smq_code'], unique=False)
            batch_op.create_index('idx_smq_content_term', ['term_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meddra_smq_content', schema=None) as batch_op:
        batch_op.drop_index('idx_smq_content_term')
        batch_op.drop_index('idx_smq_content_smq')

    op.drop_table('meddra_smq_content')
    with op.batch_alter_table('meddra_mdhier', schema=None) as batch_op:
        batch_op.drop_index('idx_mdhier_soc')
        batch_op.drop_index('idx_mdhier_pt')

    op.drop_table('meddra_mdhier')
    op.drop_table('meddra_llt')
    op.drop_table('meddra_soc')
    op.drop_table('meddra_smq_list')
    op.drop_table('meddra_pt')
    op.drop_table('meddra_hlt')
    op.drop_table('meddra_hlgt')
    # ### end Alembic commands ###
