"""Add detailed AI preferences to User

Revision ID: a90f1cd41066
Revises: ecabc57b82dc
Create Date: 2026-01-20 20:39:33.725597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90f1cd41066'
down_revision = 'ecabc57b82dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('custom_gemini_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('openai_api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('openai_base_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('openai_model_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('openai_model_name')
        batch_op.drop_column('openai_base_url')
        batch_op.drop_column('openai_api_key')
        batch_op.drop_column('custom_gemini_key')
        batch_op.drop_column('ai_provider')

    # ### end Alembic commands ###
