version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: askfdalabel-db
    user: $UID
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: askfdalabel
      POSTGRES_USER: afd_user
      POSTGRES_PASSWORD: afd_password
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U afd_user -d askfdalabel"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  default:
    name: askfdalabel-network
