from pg_utils import PGUtils
from psycopg2 import sql

def init_labeling_schema():
    print("Initializing 'labeling' schema in PostgreSQL...")
    PGUtils.create_schema('labeling')
    
    conn = PGUtils.get_connection()
    try:
        with conn.cursor() as cursor:
            # 1. Main Metadata Table
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS labeling.sum_spl (
                spl_id TEXT PRIMARY KEY,
                set_id TEXT,
                product_names TEXT,
                generic_names TEXT,
                manufacturer TEXT,
                appr_num TEXT,
                active_ingredients TEXT,
                market_categories TEXT,
                doc_type TEXT,
                routes TEXT,
                dosage_forms TEXT,
                epc TEXT,
                ndc_codes TEXT,
                revised_date TEXT,
                initial_approval_year INTEGER,
                is_rld INTEGER DEFAULT 0,
                is_rs INTEGER DEFAULT 0,
                local_path TEXT
            )
            """)
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_sum_spl_set_id ON labeling.sum_spl(set_id);")

            # 2. Section Content Table
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS labeling.spl_sections (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                spl_id TEXT,
                loinc_code TEXT,
                title TEXT,
                content_xml TEXT,
                search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', coalesce(content_xml, ''))) STORED,
                FOREIGN KEY(spl_id) REFERENCES labeling.sum_spl(spl_id) ON DELETE CASCADE
            )
            """)
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_spl_sections_spl_id ON labeling.spl_sections(spl_id);")
            
            # Full-Text Search Index on the STORED column
            print("Creating GIN index on pre-computed search_vector...")
            cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_spl_sections_fts ON labeling.spl_sections USING GIN (search_vector);
            """)

            # 3. Mapping Tables
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS labeling.active_ingredients_map (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                spl_id TEXT,
                substance_name TEXT,
                is_active INTEGER,
                FOREIGN KEY(spl_id) REFERENCES labeling.sum_spl(spl_id) ON DELETE CASCADE
            )
            """)
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_active_ingr_spl_id ON labeling.active_ingredients_map(spl_id);")

            cursor.execute("""
            CREATE TABLE IF NOT EXISTS labeling.epc_map (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                spl_id TEXT,
                epc_term TEXT,
                FOREIGN KEY(spl_id) REFERENCES labeling.sum_spl(spl_id) ON DELETE CASCADE
            )
            """)
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_epc_map_spl_id ON labeling.epc_map(spl_id);")

            # 4. Tracking Table for Bulk ZIPs
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS labeling.processed_zips (
                zip_name TEXT PRIMARY KEY,
                processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """)

            conn.commit()
            print("[SUCCESS] 'labeling' schema initialized.")
    except Exception as e:
        conn.rollback()
        print(f"[ERROR] Failed to initialize labeling schema: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    init_labeling_schema()
